version: '3.13'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upwards-crm
    env_file:
      - .env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app 
      - static_volume:/app/app/static
      - media_volume:/app/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    depends_on:
      - web 
    networks:
      - webnet

networks:
  webnet:  
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
