# Generated by Django 5.1.6 on 2025-02-15 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус таск', 'verbose_name_plural': 'Статусы таск'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Таск', 'verbose_name_plural': 'Таски'},
        ),
        migrations.AddField(
            model_name='project',
            name='design_reference',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
