name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    #   - name: Load environment variables
    #     run: |
    #       cp example.env .env

    #   - name: Build Docker image
    #     run: make build 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SERVER }} <<EOF
            cd /home/upwards/upwards.crm.backend/
            git pull https://${{ secrets.TOKEN }}@github.com/VibeMoon/upwards.crm.backend.git
            make down
            make build
            make up
          EOF